// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByrcKkzWEpZDiTPkSKaoqEqEaUQQuoFq0',
    appId: '1:614725527374:web:d32e6a509c2100f5b8601f',
    messagingSenderId: '614725527374',
    projectId: 'theshelf-e0726',
    authDomain: 'theshelf-e0726.firebaseapp.com',
    storageBucket: 'theshelf-e0726.firebasestorage.app',
    measurementId: 'G-CN6W771E2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTn4h3-ilam3iQmWplwTD7NZ6Br_QZadI',
    appId: '1:614725527374:android:b02f7f47fbcb9d52b8601f',
    messagingSenderId: '614725527374',
    projectId: 'theshelf-e0726',
    storageBucket: 'theshelf-e0726.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyhDOJMBD8GIHuPAGFIiOZaIegilWfh_A',
    appId: '1:614725527374:ios:be0a9ba76b7f8007b8601f',
    messagingSenderId: '614725527374',
    projectId: 'theshelf-e0726',
    storageBucket: 'theshelf-e0726.firebasestorage.app',
    iosBundleId: 'com.example.bookReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyhDOJMBD8GIHuPAGFIiOZaIegilWfh_A',
    appId: '1:614725527374:ios:be0a9ba76b7f8007b8601f',
    messagingSenderId: '614725527374',
    projectId: 'theshelf-e0726',
    storageBucket: 'theshelf-e0726.firebasestorage.app',
    iosBundleId: 'com.example.bookReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByrcKkzWEpZDiTPkSKaoqEqEaUQQuoFq0',
    appId: '1:614725527374:web:d10d1f71f56da398b8601f',
    messagingSenderId: '614725527374',
    projectId: 'theshelf-e0726',
    authDomain: 'theshelf-e0726.firebaseapp.com',
    storageBucket: 'theshelf-e0726.firebasestorage.app',
    measurementId: 'G-3H7JJ619LZ',
  );
}
