// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZcvXwxwA_kl5cYeJiVj8JLu7rL9RXGA',
    appId: '1:168124375318:web:cf6b697461af401934f037',
    messagingSenderId: '168124375318',
    projectId: 'theshelf-61b6f',
    authDomain: 'theshelf-61b6f.firebaseapp.com',
    storageBucket: 'theshelf-61b6f.firebasestorage.app',
    measurementId: 'G-7QVMMZY7LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BmECcjbMAwOy351H3JWvJqX6xO9dZj8',
    appId: '1:168124375318:android:311d6efada0ee6c034f037',
    messagingSenderId: '168124375318',
    projectId: 'theshelf-61b6f',
    storageBucket: 'theshelf-61b6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8MuYhkd0M-rBhYIoBN-8qDQEANIHb80',
    appId: '1:168124375318:ios:866351d06591601234f037',
    messagingSenderId: '168124375318',
    projectId: 'theshelf-61b6f',
    storageBucket: 'theshelf-61b6f.firebasestorage.app',
    iosBundleId: 'com.example.bookReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX8MuYhkd0M-rBhYIoBN-8qDQEANIHb80',
    appId: '1:168124375318:ios:866351d06591601234f037',
    messagingSenderId: '168124375318',
    projectId: 'theshelf-61b6f',
    storageBucket: 'theshelf-61b6f.firebasestorage.app',
    iosBundleId: 'com.example.bookReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjZcvXwxwA_kl5cYeJiVj8JLu7rL9RXGA',
    appId: '1:168124375318:web:95a4cafd83bb9d3134f037',
    messagingSenderId: '168124375318',
    projectId: 'theshelf-61b6f',
    authDomain: 'theshelf-61b6f.firebaseapp.com',
    storageBucket: 'theshelf-61b6f.firebasestorage.app',
    measurementId: 'G-E9KPELF9P0',
  );

}